approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableScripts: true

nodeLinker: node-modules

npmPreapprovedPackages:
  - "@emaarco/dmn-js-simulation"
  - "@miragon/create-append-c7"
  - "bpmnlint"

npmScopes:
  miragon:
    npmRegistryServer: "https://registry.npmjs.org"
