"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "corepack yarn install"
run = "corepack yarn workspace @miragon/bpmn-modeler-webview dev"
archive = "rm -rf dist node_modules"

run_mode = "concurrent"
auto_run_after_setup = true
