[versions]
kotlin = "2.4.0"
intellijPlatform = "2.16.0"
gson = "2.14.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
