import { ScriptKind } from "@miragon/bpmn-modeler-shared";

import { beansFor, COMPLEX_TYPES, globalFunctionsFor, MethodDef, MethodParam } from "./scriptApi";

/**
 * Generates the ambient `camunda.d.ts` placed next to a JavaScript inline
 * script so *tsserver* — not our completion provider — serves typed bean and
 * SPIN completion.
 *
 * Exists because VS Code's suggest model is winner-takes-all by provider
 * group: only suggestions coming from the same language service that owns the
 * file merge with locals, hover and signature help. Declaring the kind-scoped
 * beans ambiently gives JavaScript users the full tsserver experience and
 * lets the built-in provider retire its static JS catalog. Process variables
 * stay on the provider — a static d.ts cannot express them.
 */

/**
 * Maps the catalog's Java-flavoured type labels to TypeScript. Catalog
 * interface names pass through (they are declared in the same file); the
 * fallback is `any` so an unmapped label degrades to untyped rather than to a
 * compile error inside the generated ambient file.
 */
const COMPLEX_TYPE_NAMES = new Set(COMPLEX_TYPES.map((type) => type.name));

const JAVA_TO_TS: ReadonlyMap<string, string> = new Map([
    ["String", "string"],
    ["int", "number"],
    ["long", "number"],
    ["double", "number"],
    ["Number", "number"],
    ["Boolean", "boolean"],
    ["boolean", "boolean"],
    ["void", "void"],
    ["Object", "any"],
    ["Map<String, Object>", "Record<string, any>"],
    ["Set<String>", "string[]"],
    ["List<String>", "string[]"],
    ["SpinList<SpinJsonNode>", "SpinJsonNode[]"],
]);

function tsType(javaLabel: string): string {
    if (COMPLEX_TYPE_NAMES.has(javaLabel)) {
        return javaLabel;
    }
    return JAVA_TO_TS.get(javaLabel) ?? "any";
}

function tsParams(params: readonly MethodParam[]): string {
    return params.map((param) => `${param.name}: ${tsType(param.type)}`).join(", ");
}

function methodSignature(method: MethodDef): string {
    return `    /** ${method.description} */\n    ${method.name}(${tsParams(method.params)}): ${tsType(method.returnType)};`;
}

/**
 * Renders the ambient declaration file for one script kind.
 *
 * All catalog interfaces are always emitted (they cross-reference each other
 * in return types); only the *bean constants* and *global functions* are
 * scoped — beans by kind, SPIN globals by the host's SPIN setting.
 */
export function generateCamundaDts(kind: ScriptKind, spinEnabled: boolean): string {
    const sections: string[] = [
        "// Generated by the Miragon BPMN Modeler for the open inline script.",
        "// Do not edit — recreated on every script open and deleted with it.",
        "",
    ];

    for (const type of COMPLEX_TYPES) {
        sections.push(`/** ${type.description} */`);
        sections.push(`interface ${type.name} {`);
        sections.push(...type.methods.map(methodSignature));
        sections.push("}", "");
    }

    for (const bean of beansFor(kind)) {
        sections.push(`/** ${bean.description} */`);
        sections.push(`declare const ${bean.name}: ${tsType(bean.type)};`, "");
    }

    if (spinEnabled) {
        for (const fn of globalFunctionsFor(kind)) {
            sections.push(`/** ${fn.description} */`);
            sections.push(
                `declare function ${fn.name}(${tsParams(fn.params)}): ${tsType(fn.returnType)};`,
                "",
            );
        }
    }

    return sections.join("\n");
}

/**
 * Minimal `jsconfig.json` written next to the script and its `camunda.d.ts`.
 *
 * tsserver puts a loose JavaScript file into an *inferred* project that does
 * not include sibling declaration files; a config file in the same directory
 * makes tsserver create a configured project containing the whole directory
 * (script + d.ts) — and, because the nearest config wins, also shields the
 * script from any tsconfig at the workspace root.
 */
export const SCRIPT_JSCONFIG = `${JSON.stringify(
    {
        compilerOptions: { checkJs: false, allowJs: true },
        include: ["*.js", "*.d.ts"],
    },
    null,
    4,
)}\n`;
